services:
  adminer:
    image: adminer:latest
    container_name: refugio-adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - postgres-db
    networks:
      - refugio-net

  # Servicio de Base de Datos PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: refugio-db
    environment:
      POSTGRES_DB: refugio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata_refugio:/var/lib/postgresql/data
    networks:
      - refugio-net

  # Servicio de la Aplicación Web (Open Liberty)
  refugio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refugio-web-app
    ports:
      - "9080:9080"
      - "9443:9443"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: refugio_db
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
    depends_on:
      - postgres-db
    networks:
      - refugio-net


volumes:
  pgdata_refugio:

networks:
  refugio-net:
    driver: bridge